// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using realtime_service.Data;

#nullable disable

namespace realtime_service.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250814030420_AddTableNotification")]
    partial class AddTableNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("realtime_service.Entity.Message", b =>
                {
                    b.Property<int>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("message_id"));

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("read_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("receiver_id")
                        .HasColumnType("int");

                    b.Property<string>("receiver_snapshot_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sender_id")
                        .HasColumnType("int");

                    b.Property<string>("sender_snapshot_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sent_at")
                        .HasColumnType("datetime2");

                    b.HasKey("message_id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("realtime_service.Entity.Notification", b =>
                {
                    b.Property<int>("notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notification_id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("message_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("notification_id");

                    b.ToTable("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
